# These are supported funding model platforms

github: [itsrohan-lang] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: itsrohan # Replace with a single Patreon username
open_collective: stuntdouble # Replace with a single Open Collective username
ko_fi: rohan # Replace with a single Ko-fi username
custom: ["https://buymeacoffee.com/rohan"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
