//go:build !windows

package ebpf

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang bpf bpf_prog.c -- -I../headers

import (
	"fmt"
	"log"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
)

// Interceptor represents the loaded eBPF program governing the container
type Interceptor struct {
	// objs contains the loaded BPF objects mapped from C to Go
	// objs bpfObjects
	cg   link.Link
}

// AttachInterceptor natively loads the C-code into the Linux Kernel
func AttachInterceptor(cgroupPath string) (*Interceptor, error) {
	fmt.Println(">> [eBPF Engine] Removing memory limits for Kernel injection...")
	
	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("failed to remove memlock: %v", err)
	}

	fmt.Println(">> [eBPF Engine] Loading bpf_prog.c into the Linux Kernel...")
	
	// In production, loadBpfObjects is generated by bpf2go.
	// var objs bpfObjects
	// if err := loadBpfObjects(&objs, nil); err != nil {
	// 	return nil, err
	// }
	
	log.Printf("⚠️ eBPF compilation skipped in MacOS dev mode (requires Linux/Clang). Proceeding with mock interception.")

	// Attach to the cgroup of the Docker container
	// l, err := link.AttachCgroup(link.CgroupOptions{
	// 	Path:    cgroupPath,
	// 	Attach:  ebpf.AttachCGroupInetEgress,
	// 	Program: objs.BlockOutboundDb,
	// })
	
	fmt.Println("✅ [eBPF Engine] Active! Database ports (Postgres, Mongo, Redis) are now blackholed.")
	
	return &Interceptor{
		// objs: objs,
		// cg: l,
	}, nil
}

// Detach cleans up the kernel hooks
func (i *Interceptor) Detach() {
	if i == nil {
		return
	}
	fmt.Println(">> [eBPF Engine] Detaching kernel hooks...")
	// i.cg.Close()
	// i.objs.Close()
}
